version: "3"
services:
  rgtac:
    image: rgtac
    container_name: rgtac
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: rgtac.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: rgtac.com
    restart: unless-stopped

networks:
  default:
    name: nginx-proxy
